##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. See LICENSE file
## in the root directory.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_generate_dart_models
description: A tool to generate index/exports files for all Dart files in a directory.
version: 0.1.3
repository: https://github.com/robmllze/df_generate_dart_models

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.0.0 < 4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  analyzer: ^6.8.0
  args: ^2.5.0
  path: ^1.9.0
  df_collection: ^0.1.2
  df_config: ^0.1.1
  df_gen_core: ^0.1.2
  df_generate_dart_models_core: ^0.1.2
  df_log: ^0.1.1
  df_string: ^0.1.0
  df_type: ^0.1.2

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

## -----------------------------------------------------------------------------

executables:
  df_generate_dart_models: generate_dart_models
  generate_dart_models: generate_dart_models
  dartmodels: generate_dart_models
