##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. The use of this
## source code is governed by an MIT-style license described in the LICENSE
## file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_generate_dart_models
description: A tool for generating data models and classes from annotations, offering greater flexibility than json_serializable or freezed.
version: 0.10.0
repository: https://github.com/robmllze/df_generate_dart_models
funding:
  - https://www.buymeacoffee.com/robmllze
topics:
  - build-runner
  - cli
  - codegen
  - freezed
  - json-serializable

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  df_collection: ^0.8.1
  df_config: ^0.5.1
  df_gen_core: ^0.4.4
  df_generate_dart_models_core: ^0.6.10
  df_log: ^0.2.4
  df_string: ^0.2.2
  df_type: ^0.7.2

  analyzer: ^6.8.0
  args: ^2.5.0
  path: ^1.9.0
  google_generative_ai: ^0.4.6

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8

## -----------------------------------------------------------------------------

executables:
  dfmdl: dfmdl_dart
  dfmdl-basic: dfmdl_dart_basic
  dfmdl-dart-amplify: dfmdl_dart_amplify
  dfmdl-dart-js: dfmdl_dart_js
  dfmdl-dart-py: dfmdl_dart_py
  dfmdl-dart-ts: dfmdl_dart_ts
  dfmdl-dart-tstype: dfmdl_dart_tstype
