##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. The use of this
## source code is governed by an MIT-style license described in the LICENSE
## file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_generate_dart_models
description: A tool to generate index/exports files for all Dart files in a directory.
version: 0.5.0
repository: https://github.com/robmllze/df_generate_dart_models
funding:
  - https://www.buymeacoffee.com/robmllze
topics:
  - build-runner
  - cli
  - codegen
  - freezed
  - json-serializable

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  df_collection: ^0.6.0
  df_config: ^0.5.0
  df_gen_core: ^0.3.0
  df_generate_dart_models_core: ^0.5.0
  df_log: ^0.2.4
  df_string: ^0.2.2
  df_type: ^0.6.1

  analyzer: ^6.8.0
  args: ^2.5.0
  path: ^1.9.0

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^5.0.0

## -----------------------------------------------------------------------------

executables:
  genmdl: genmdl_dart
  genmdl-dart: genmdl_dart
