##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. The use of this
## source code is governed by an MIT-style license described in the LICENSE
## file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_generate_dart_models
description: A tool to generate index/exports files for all Dart files in a directory.
version: 0.2.4
repository: https://github.com/robmllze/df_generate_dart_models

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.0.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  analyzer: ^6.8.0
  args: ^2.5.0
  df_collection: ^0.2.0
  df_config: ^0.1.2
  df_gen_core: ^0.2.2
  df_generate_dart_models_core: ^0.2.3
  df_log: ^0.1.2
  df_string: ^0.1.2
  df_type: ^0.1.4
  path: ^1.9.0

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8

## -----------------------------------------------------------------------------

executables:
  df_generate_dart_models: generate_dart_models
  generate_dart_models: generate_dart_models
  dartmodels: generate_dart_models
